name: MaCoreCommodore
version: 0.0.2
main: pl.mateam.marpg.core.MaCoreCommodoreEngine
depend: [ProtocolLib, Citizens]

author: Marcoral
description: "Jedynie MaCoreCommodore, najpotężniejszy znany plugin-matka, pozwala powołać serwer MaRPG do działania."
website: www.marpg.pl