package pl.mateam.marpg.api.regular.enums.items;

public enum CommonSpecialItem {
	PICKAXE_LEVEL_5(-33),
	PICKAXE_LEVEL_4(-32),
	PICKAXE_LEVEL_3(-31),
	PICKAXE_LEVEL_2(-30),
	PICKAXE_LEVEL_1(-29),

	DEFAULT_RING(-28),
	DEFAULT_NECKLACE(-27),

	DEFAULT_SLAYER_SHIELD(-26),
	DEFAULT_MAGE_SHIELD(-25),
	DEFAULT_BARBARIAN_SHIELD(-24),
	DEFAULT_WARRIOR_SHIELD(-23),
	
	DEFAULT_SLAYER_BOOTS(-22),
	DEFAULT_MAGE_BOOTS(-21),
	DEFAULT_BARBARIAN_BOOTS(-20),
	DEFAULT_WARRIOR_BOOTS(-19),
	
	DEFAULT_SLAYER_LEGGINGS(-18),
	DEFAULT_MAGE_LEGGINGS(-17),
	DEFAULT_BARBARIAN_LEGGINGS(-16),
	DEFAULT_WARRIOR_LEGGINGS(-15),

	DEFAULT_SLAYER_CHESTPLATE(-14),
	DEFAULT_MAGE_CHESTPLATE(-13),
	DEFAULT_BARBARIAN_CHESTPLATE(-12),
	DEFAULT_WARRIOR_CHESTPLATE(-11),

	DEFAULT_SLAYER_HELMET(-10),
	DEFAULT_MAGE_HELMET(-9),
	DEFAULT_BARBARIAN_HELMET(-8),
	DEFAULT_WARRIOR_HELMET(-7),
	
	DEFAULT_SWORD(-6),
	DEFAULT_HAMMER(-5),
	DEFAULT_AXE(-4),
	DEFAULT_GREATSWORD(-3),
	DEFAULT_STAFF(-2),
	DEFAULT_DAGGER(-1);

	public int getID()	{	return ID;	}
	private final int ID;
	private CommonSpecialItem(int ID) {	this.ID = ID;	}
}
